version: "3.1"

services:
  liquidator-main:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - keypair # secret to encrypte wallet details in container

secrets:
  keypair:
    file: ./keypairs/BMJPDSLMF2R7rJwJ7FKdrTJH8kSQaN6qiS6V4Ly7Y9YP.json
    